hash-format = "sha256"

[[files]]
file = ".docker-compose.yml.kate-swp"
hash = "ace7c7824a998cf5b607847296ed84849f4fdad4d540e46686edfb9d5f63f66f"

[[files]]
file = "docker-compose.yml"
hash = "b5a61df1811db586647fdabcf7ef18d5ba002da373bb7b331fadb1e29a1129c7"

[[files]]
file = "mods/almanac-lib.pw.toml"
hash = "49a33ac37445e3c08eb1a958b4f81f0c9ce356a8c08ace17e5df98e18558b4b1"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "e1dc1bb8a3537b9c5b41cbc6fa97f19729d6c9ab602810da0b192c5fc84eba7e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/convenient-mobgriefing.pw.toml"
hash = "c9127c8a26671e16730352e42f67894eafe69ee54d0640f05d45f95502b817e2"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "55eb77cf033ffd79fa41d06d87185c0fa3ff2c1b0f5605ad64aa52e0613a44bc"
metafile = true

[[files]]
file = "mods/entity-view-distance.pw.toml"
hash = "00de73f44c85bbe43476ba1e19098a6d0e2180bec7bdbf8199ff482e21a3a8cc"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "336bea7fbe2bbbae3875ac59dbc0d11a7f1eb247a5f23e951c136bcd952a6086"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "e55434d8c10a69fb660cf66c6daaeda8c4ce83f53824186954e9fccac43e8a01"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "9a8c273d0efcf679d04d77ab37521c05978caff642a6c2b867d2fa2cdc8b168e"
metafile = true

[[files]]
file = "mods/fuji.pw.toml"
hash = "593e4347238a1f38c97a7b28c0b1b48b358a43ba5be2282dfa41b6cf66debb48"
metafile = true

[[files]]
file = "mods/get-it-together-drops.pw.toml"
hash = "8bb5b5695810c5f5eb27a4e1890db7492ec4ad0c6efe95e713f694aa017e640d"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "2b6bf4bb986325e04b07089ffcbbcc814fe503ddf45dd126b336a32b170eacd0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed9d0d5d4078c137900006321d35515cee46058b92df1128ea37cda3e5e1bb2b"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ffd2bde70110ba1d26bf841930556307a5bdfa3159b194e6e30ac5192be61754"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "78eb7a4883effdbab78ff513fba684e62783bad2ef54b1aeef0fe584af490c67"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/notica.pw.toml"
hash = "9e3cf867176b5e96f7ac0ba8a8cd6814df93d97b4ec13fcd1d0ccc0d3a1cfe0a"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d788235233cd7bb10444760f354161d730ce1c504976cfdf91bd26fcd05c9e26"
metafile = true

[[files]]
file = "mods/seedguard.pw.toml"
hash = "d574929c48ee577c63e3dd7629b2f68a26f396d36af96306022edf793e4b7195"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "886b70d966a36dca61cbd19c4d3955ed657206ce9b8491aad7894c0a369355cd"
metafile = true

[[files]]
file = "mods/sessility.pw.toml"
hash = "f9bdec68d0fbc4d4e3ed1d8164a1451dd112b34954fc679bfab9b382ba1c5c25"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "bc51a87dbb634a67e8f194ed80c4af4638e5fcc0bc0c1fbe4b1828882ec14403"
metafile = true

[[files]]
file = "mods/slumber.pw.toml"
hash = "fabf3dbf6c00a57c519cb4359fbcc7fa73be6bf1477004472917263f21b7197e"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/vanilla-permissions.pw.toml"
hash = "dd27fa8950077843a03363fd36ef344bb11ca9759c44a4f3f281678cb5da688e"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "79a938585866f8f74e569d39fb968b5bb9300634b79f537149f7494eb427d940"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "90df8d95fcd836373dd1b26dd8f3fbc6ca8ac55f797e09562796aa0aeb0576c0"
metafile = true
