name = "FCP+"
author = "GG45(gabriel)"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fdec1fb46ade7b0f8b9d3265b11ba532378ada7f5ee98b25cae768be6096e64"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
