name = "FCP - Fabric Cross Play PLUS"
author = "GG45(gabriel)"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0656c843c65148a6afefc122980d796a4f75627998cf073aa434fc89e598ad86"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
